// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminderChallenge.Repository;

#nullable disable

namespace ReminderChallenge.Repository.Migrations
{
    [DbContext(typeof(ReminderContext))]
    [Migration("20250502002406_ChangeTypeExpirationInReminder")]
    partial class ChangeTypeExpirationInReminder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ReminderChallenge.Repository.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("reminder_id");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condominium_id");

                    b.Property<DateTime>("CreateAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<int>("TypeExpiration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expiration_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Reminder", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
